---
- name: Download helm.tar.gz
  get_url:
    url: https://get.helm.sh/helm-v3.14.0-linux-amd64.tar.gz
    dest: /tmp/helm.tar.gz

- name: Extract helm.tgz into /tmp/
  unarchive:
    src: /tmp/helm.tar.gz
    dest: /tmp/
    remote_src: yes

- name: Move Helm binary to /usr/local/bin
  become: yes
  copy:
    src: /tmp/linux-amd64/helm
    dest: /usr/local/bin/helm
    mode: '0755'
    remote_src: yes

- name: Ensure Helm is working
  command: helm version
  register: helm_output
  changed_when: false
  become: yes

- name: Print Helm version
  debug:
    msg: "{{ helm_output.stdout_lines }}"
